name: ios_objc_mix

targets:
  ios_objc_mix:
    type: application
    platform: iOS
    sources:
      - path: ios_objc_mix
    settings:
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        MARKETING_VERSION: 1.3.3
        CURRENT_PROJECT_VERSION: "14"
        SWIFT_OBJC_BRIDGING_HEADER: ios_objc_mix/ios_objc_mix-Bridging-Header.h
        INFOPLIST_FILE: "ios_objc_mix/Info.plist"
        DEVELOPMENT_TEAM: 6HPVY63L4K
        SWIFT_OBJC_INTERFACE_HEADER_NAME: toto-Swift.h
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
        PRODUCT_MODULE_NAME: ios_objc_mix
        GCC_PREFIX_HEADER: ios_objc_mix/ios_objc_mix-PrefixHeader.pch
        CODE_SIGN_STYLE: Manual
        ONLY_ACTIVE_ARCH: "YES"
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        PRODUCT_BUNDLE_IDENTIFIER: AFS.Retraite.ARE-RECETTE
        SWIFT_VERSION: 5
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: MixTest
  
  MixTest:
    platform: iOS
    type: bundle.unit-test
    deploymentTarget: 17
    sources:
      - path: ios_objc_mixTests
    settings:
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        INFOPLIST_FILE: "ios_objc_mix/Info.plist"
        SWIFT_VERSION: 5
    dependencies:
      - target: ios_objc_mix
    scheme:
      management:
        isShown: false





